# Generated by Django 4.2.4 on 2023-08-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('restaurants', '0002_restaurants_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='image',
            field=models.ImageField(blank=True, default='pythons-logo.jpg', upload_to='restaurants_logos'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.product'),
        ),
    ]
