# Generated by Django 4.2.4 on 2023-08-16 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('about_service', models.TextField()),
                ('service_logo', models.ImageField(blank=True, default='default_service_logo.jpg', upload_to='service_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('is_delivered', models.CharField(choices=[("('Pending', 'pending')", 'Pending'), ("('In transit', 'in Transit')", 'In Transit'), ('Is Delivered', 'is delivered')], default="('Pending', 'pending')", max_length=50)),
                ('products', models.ManyToManyField(to='products.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
