# Generated by Django 4.2.4 on 2023-08-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_services', '0002_delete_deliveryservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='products',
        ),
    ]
