# Generated by Django 4.2.4 on 2023-08-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delivery'),
        ('delivery_services', '0003_remove_delivery_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_services.delivery')),
                ('pruduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
